name: BuildAndPublish
on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
  pull_request: 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet 3
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: build and publish
        shell: pwsh
        run: |
          ./build.ps1 -nugetPublish $false -nugetApiKey ${{ secrets.NUGET_API_KEY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nuget-packages
          path: artifacts/NuGet